### ISSUE TITLE
Start using feature enums to value (umbrella issue)

### ISSUE THREAD

**Issue by asfimport** [apache/arrow-java#334]
Proposed logic:

1.  Add flag where appropriate for supports dictionary replacement if there is a possibility it can be used.

2.  Only add compressed buffers when requested.

 

Reading should validate enums are in range AND implementation supports them.

**Reporter**: [Micah Kornfield](https://issues.apache.org/jira/browse/ARROW-9309) / @emkornfield
#### Subtasks:
- [ ] [[Java] Use feature enum](https://github.com/apache/arrow-java/issues/333)
- [ ] [[JS] Use feature enum in javascript](https://github.com/apache/arrow/issues/25399)
- [ ] [[C++] Use feature enum](https://github.com/apache/arrow/issues/25400)
- [X] [[Rust] Use feature enum](https://github.com/apache/arrow/issues/25401)
- [ ] [[Go] Use Feature enum](https://github.com/apache/arrow-go/issues/73)

<sub>**Note**: *This issue was originally created as [ARROW-9309](https://issues.apache.org/jira/browse/ARROW-9309). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>
